version: '2'
services:
  php:
    image: bscheshir/php:7.2.0-fpm-alpine-4yii2
    restart: always
    volumes:
      - ./php-code:/var/www/html #php-code
      - ~/.composer/cache:/root/.composer/cache
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_enable=Off remote_autostart=Off"
  nginx:
    image: nginx:1.13.7-alpine
    restart: always
#    ports: # use nginx-proxy in same network (see ./docs/nginx-proxy.md)
#      - "8080:8080"
#      - "8081:8081"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d #nginx-conf
      - ./nginx-logs:/var/log/nginx #nginx-logs
  db:
    image: mysql:8.0.3
    entrypoint: ['/entrypoint.sh', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    restart: always
    volumes:
      - ./mysql-data/db:/var/lib/mysql #mysql-data
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: yii2advanced
      MYSQL_DATABASE: yii2advanced
      MYSQL_USER: yii2advanced
      MYSQL_PASSWORD: yii2advanced
