version: '2'
services:
  php:
    image: bscheshir/php:7.2.5-fpm-alpine-4yii2-xdebug
    restart: always
    volumes:
      - ../php-code:/var/www/html #php-code
      - ~/.composer/cache:/root/.composer/cache
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_host=dev-Aspire-V3-772 remote_port=9001 remote_enable=On var_display_max_data=1024 var_display_max_depth=5"
      PHP_IDE_CONFIG: "serverName=yii2advanced"
  nginx:
    image: nginx:1.13.12-alpine
    restart: always
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ../nginx-conf-test:/etc/nginx/conf.d #nginx-conf
      - ../nginx-logs:/var/log/nginx #nginx-logs
    networks:
      default:
        aliases:
         - backend.dev
         - frontend.dev
    environment:
      TZ: Europe/Moscow
  db:
    image: mysql:8.0.11
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password'] # https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin
    restart: always
    ports:
      - "33006:3306"
    volumes:
      - ../mysql-data-test/db:/var/lib/mysql #mysql-data
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: yii2advanced
      MYSQL_DATABASE: yii2advanced
      MYSQL_USER: yii2advanced
      MYSQL_PASSWORD: yii2advanced
  codecept:
    image: bscheshir/codeception:php7.2.5-fpm-alpine-yii2
    depends_on:
      - nginx
      - browser
    volumes_from:
      - php
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_host=dev-Aspire-V3-772 remote_port=9002 remote_enable=On"
      PHP_IDE_CONFIG: "serverName=codeception"
  browser:
    image: selenium/standalone-chrome-debug:3.7
#    image: selenium/standalone-firefox-debug:3.11.0
    volumes:
      - /dev/shm:/dev/shm # the docker run instance may use the default 64MB, that may not be enough in some cases
    ports:
      - '4444'
      - '5900'
    environment:
      TZ: Europe/Moscow
